/*
  ____  _       _        _             _       
 / ___|(_)_ __ | | __  | |_ __  _   _| | __ _ _ _ __
 \___ \| | '_ \| |/ /  | '_ \| | | | | |/ _` | | '_ \
  ___) | | | | |   <   | |_) | | |_| | | (_| | | | | |
 |____/|_|_| |_|_|\_\  | .__/|_|\__,_|_|\__, |_|_| |_|
                       |_|               |___/
# A Template for RerunPlugin, a Sink Plugin
# Generated by the command: plugin -t sink -d rerun_plugin -s rerun
# Hostname: Fram-IV.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2025-09-08T16:35:50.334+0200
# NOTICE: MADS Version 1.3.5
*/

// Mandatory included headers
#include <nlohmann/json.hpp>
#include <sink.hpp>

// Include pugg on non-Windows platforms, or if we have dlfcn.h available

#include <pugg/Kernel.h>

#include "moving_window_stats.hpp"
#include "skeleton_definition.hpp"

#include <BS_thread_pool.hpp>
#include <array>
#include <chrono>
#include <datastore.hpp>
#include <deque>
#include <filesystem>
#include <future>
#include <memory>
#include <optional>
#include <rerun.hpp>
#include <unordered_map>
#include <vector>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "rerun"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
#include <deque>
#include <unordered_map>

class RerunnerPlugin : public Sink<json> {
private:
  // Skeleton configuration
  pose::SkeletonDefinition _skeleton;
  std::vector<std::string> _skeleton_keypoint_paths;

  bool _enable_skeleton = false;
  bool _enable_bones = true;
  bool _enable_keypoints = true;

  std::vector<std::string> _keypaths;
  std::vector<std::string> _acf_keypaths;
  std::vector<std::string> _fft_keypaths;
  std::vector<std::string> _trace_keypaths;
  MovingWindowStats _stats;
  size_t _window_size = 1000; // Store 10x ACF width for better statistics
  filesystem::path _blueprint;
  
  // Real-time visualization settings
  bool _enable_timeseries = true; // Automatically enable time series

  std::chrono::steady_clock::time_point _start_time;
  std::shared_ptr<rerun::RecordingStream> _rec;

  BS::thread_pool<BS::tp::none> _pool;
  vector<future<bool>> _futures;
  
  // Rate limiting to prevent gRPC overload
  size_t _frame_count = 0;
  bool _enable_rate_limiting = true;
  std::chrono::microseconds _min_frame_delay{5000}; // 5ms default to prevent overload
  std::chrono::steady_clock::time_point _last_frame_time;

  // Helper function to convert dot notation path to JSON value
  json::json_pointer dot_to_pointer(const std::string &dot_path) {
    std::string result;
    std::string token;
    bool in_brackets = false;
    if (dot_path[0] == '/') 
      return json::json_pointer(dot_path);

    for (char c : dot_path) {
      if (c == '[') {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
        in_brackets = true;
      } else if (c == ']') {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
        in_brackets = false;
      } else if (c == '.' && !in_brackets) {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
      } else {
        token += c;
      }
    }

    if (!token.empty()) {
      result += "/" + token;
    }

    return json::json_pointer(result);
  }

  // Helper function to safely get a value from JSON using dot notation
  std::optional<double> get_numeric_value(const json &j,
                                          const std::string &dot_path) {
    json::json_pointer ptr = dot_to_pointer(dot_path);

    try {
      const auto &value = j[ptr];

      if (value.is_number()) {
        return value.get<double>();
      }
    } catch (const json::exception &e) {
      // Path doesn't exist or other JSON error
    }
    return std::nullopt;
  }

  // Helper: Extract 3D position from JSON keypath
  // Supports both /path/x, /path/y, /path/z AND /path/crd/0, /path/crd/1, /path/crd/2
  std::optional<std::array<double, 3>> extract_3d_position(const json &data, const std::string &keypath) {
      // Try new format first: /JOINT/crd/0, /JOINT/crd/1, /JOINT/crd/2
      auto x_val = get_numeric_value(data, keypath + "/crd/0");
      auto y_val = get_numeric_value(data, keypath + "/crd/1");
      auto z_val = get_numeric_value(data, keypath + "/crd/2");
      
      // Fall back to old format: /path/x, /path/y, /path/z
      if (!x_val) x_val = get_numeric_value(data, keypath + "/x");
      if (!y_val) y_val = get_numeric_value(data, keypath + "/y");
      if (!z_val) z_val = get_numeric_value(data, keypath + "/z");
      
      if (x_val && y_val && z_val) {
          return std::array<double, 3>{*x_val, *y_val, *z_val};
      }
      return std::nullopt;
  }

  // Color by confidence (red=low, green=high)
  rerun::Color confidence_to_color(double confidence) {
      confidence = std::max(0.0, std::min(1.0, confidence));
      uint8_t red = static_cast<uint8_t>((1.0 - confidence) * 255);
      uint8_t green = static_cast<uint8_t>(confidence * 255);
      return rerun::Color(red, green, 100, 255);
  }

public:
  RerunnerPlugin() {
    _start_time = std::chrono::steady_clock::now();
    _last_frame_time = _start_time;
    _frame_count = 0;
  }

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "") override {
    static double prev_time = 0;
    static double mean_dt = 0;
    static size_t n = 0;
    double dt = 0;
    bool logged = false;
    if (topic.empty()) {
      _error = "No topic specified in plugin load_data()";
      return return_type::error;
    }

    auto now = std::chrono::steady_clock::now();
    double time_seconds;
    // get the timecode from the input json if available, otherwise use elapsed
    // time
    if (!_params["time"].empty() && input.contains(_params["time"])) {
      time_seconds = input[_params["time"]].get<double>();
    } else {
      time_seconds = std::chrono::duration<double>(now - _start_time).count();
    }

    dt = time_seconds - prev_time;

    // embed the input json within a parent object named as the topic
    // keep a copy (no move) so we can attempt alternative lookup paths
    json data = json{{topic, input}};
    
    // Rate limiting: prevent flooding gRPC connection
    if (_enable_rate_limiting && _frame_count > 0) {
      auto now_time = std::chrono::steady_clock::now();
      auto elapsed = std::chrono::duration_cast<std::chrono::microseconds>(now_time - _last_frame_time);
      if (elapsed < _min_frame_delay) {
        std::this_thread::sleep_for(_min_frame_delay - elapsed);
      }
      _last_frame_time = std::chrono::steady_clock::now();
    } else if (_frame_count == 0) {
      _last_frame_time = std::chrono::steady_clock::now();
    }
    
    // Set the current time for this batch of data
    // This is crucial for time series visualization - all subsequent logs will use this timestamp
    try {
      _rec->set_time_seconds("time", time_seconds);
    } catch (const std::exception& e) {
      // Silently handle timing errors - don't fail the entire frame
      if (_frame_count % 100 == 0) {
        _error = "Warning: Rerun timing error: " + std::string(e.what());
      }
    }
    
    // Debug: Log that we're processing data (only for first few frames)
    if (n < 5) {
      try {
        _rec->log("debug/info", rerun::TextLog("Processing frame " + std::to_string(n) + 
                                               " for topic: " + topic + 
                                               " at time: " + std::to_string(time_seconds)));
      } catch (const std::exception& e) {
        // Ignore debug log errors
      }
    }

    // Extract values for each keypath and send to rerun as time series
    // Real-time visualization enabled by default
    if (_enable_timeseries && !_keypaths.empty()) {
      for (const auto &keypath : _keypaths) {
        if (auto value = get_numeric_value(data, keypath)) {
          try {
            // Log raw data point on the timeline for real-time visualization
            _rec->log("timeseries/" + keypath, rerun::Scalars(*value));
            logged = true;
          } catch (const std::exception& e) {
            if (_frame_count % 100 == 0) {
              _error = "Rerun gRPC error (timeseries/keypaths): " + std::string(e.what());
            }
          }
        }
      }
    }

    // Log skeleton visualization if enabled
    if (_enable_skeleton && !_skeleton_keypoint_paths.empty()) {
      std::vector<std::array<float, 3>> joint_positions = {};
      
      // Extract all keypoint positions and log coordinates as time series
      for (size_t i = 0; i < _skeleton_keypoint_paths.size(); ++i) {
        const auto& kp_path = _skeleton_keypoint_paths[i];

        // Build alternative paths to match incoming JSON keys
        const std::string full_path = "/" + topic + kp_path;        // e.g. /topic/ANKL
        const std::string raw_path = kp_path;                        // e.g. /ANKL
        const std::string topic_prefixed_no_slash = topic + kp_path; // e.g. topic/ANKL

        std::optional<std::array<double, 3>> pos;
        pos = extract_3d_position(data, full_path);
        if (!pos) pos = extract_3d_position(data, raw_path);
        if (!pos) pos = extract_3d_position(data, topic_prefixed_no_slash);
          
        if (pos) {
          joint_positions.push_back({static_cast<float>(pos->at(0)), static_cast<float>(pos->at(1)), static_cast<float>(pos->at(2))});
        }

      }
      
      // Log keypoints in 3D view
      if (_enable_keypoints && !joint_positions.empty()) {
          try {
            _rec->log("skeleton/keypoints", rerun::Points3D(joint_positions).with_colors(rerun::Color(255, 0, 0, 255)).with_radii({5.0f}));
            logged = true;
          } catch (const std::exception& e) {
            // gRPC connection error
            if (_frame_count % 100 == 0) {
              _error = "Rerun gRPC error (keypoints): " + std::string(e.what());
            }
          }
      }
      
      
      // Log bones in 3D view
      if (_enable_bones && !joint_positions.empty()) {
          std::vector<std::vector<std::array<float, 3>>> bone_joints_positions;
          
          for (const auto& bone : _skeleton.bones()) {
              if (bone.start_joint < joint_positions.size() && bone.end_joint < joint_positions.size()) {
                bone_joints_positions.push_back({joint_positions[bone.start_joint], joint_positions[bone.end_joint]});
              }
          }
          
          if (!bone_joints_positions.empty()) {
              try {
                _rec->log("skeleton/bones",
                          rerun::LineStrips3D(bone_joints_positions).with_colors(rerun::Color(255, 0, 0, 255)));
                logged = true;
              } catch (const std::exception& e) {
                // gRPC connection error
                if (_frame_count % 100 == 0) {
                  _error = "Rerun gRPC error (bones): " + std::string(e.what());
                }
              }
          }
      }
      
    }

    if (logged) {
      prev_time = time_seconds;
      n++;
      _frame_count++;
      
      // Ensure data is flushed to Rerun (helps with real-time visualization)
      // Note: This may slow down processing but ensures data is sent
      
      return return_type::success;
    } else {
      // No data was logged - this could indicate a configuration issue
      _frame_count++;
      return return_type::success;
    }
  }

  void set_params(void const *params) override {
    // Call the parent class method to set the common parameters
    // (e.g. agent_id, etc.)
    Sink::set_params(params);

    // provide sensible defaults for the parameters
    _params["keypaths"] = json::array();       // empty array by default
    _params["acf_keypaths"] = json::array();   // empty array by default
    _params["fft_keypaths"] = json::array();   // empty array by default
    _params["trace_keypaths"] = json::array(); // empty array by default
    _params["window_size"] = 100;              // default ACF width
    _params["time"] = "timecode";
    _params["blueprint"] = "";
    _params["parallelize"] = true;

    // then merge the defaults with the actually provided parameters
    _params.merge_patch(*(json *)params);
    _window_size = _params.value("window_size", 200);
    _stats.reset(_window_size);

    // Initialize Rerun with real-time optimized settings
    _rec = std::make_shared<rerun::RecordingStream>("MADS " + _params.value("agent_name", "rerunner (generic)"));
    _rec->spawn().exit_on_failure();

    if (!_agent_id.empty()) {
      _rec->send_recording_name(_agent_id);
    }

    _blueprint = _params.value("blueprint", "");
    if (filesystem::exists(_blueprint)) {
      _rec->log_file_from_path(_blueprint);
    } else if (!_blueprint.empty()) {
      _blueprint = _params.value("blueprint", "") + " (not found)";
    }

    // Load skeleton configuration
    if (_params.contains("skeleton_type")) {
        std::string skeleton_type = _params["skeleton_type"].get<std::string>();
        if (skeleton_type == "hpe_18") {
            _skeleton = pose::SkeletonDefinition::hpe_18();
        } else {
            // Default to HPE 18 for HPE replay datasets
            _skeleton = pose::SkeletonDefinition::hpe_18();
        }
        _enable_skeleton = true;
    } else {
        // Default skeleton
        _skeleton = pose::SkeletonDefinition::hpe_18();
        _enable_skeleton = true;
    }

    // Load keypoint paths
    _skeleton_keypoint_paths.clear();
    if (_params.contains("skeleton_keypoint_paths") && 
        _params["skeleton_keypoint_paths"].is_array()) {
        for (const auto &path : _params["skeleton_keypoint_paths"]) {
            if (path.is_string()) {
                _skeleton_keypoint_paths.push_back(path.get<std::string>());
            }
        }
    } else {
        // Auto-configure HPE 18-joint keypoint paths from CSV structure
        // Each joint has format /JOINT_NAME/crd/X for coordinates
        _skeleton_keypoint_paths = {
            "/NOS_",  // 0: NOSE
            "/NEC_",  // 1: NECK
            "/SHOL",  // 2: LEFT_SHOULDER
            "/SHOR",  // 3: RIGHT_SHOULDER
            "/ELBL",  // 4: LEFT_ELBOW
            "/ELBR",  // 5: RIGHT_ELBOW
            "/WRIL",  // 6: LEFT_WRIST
            "/WRIR",  // 7: RIGHT_WRIST
            "/HIPL",  // 8: LEFT_HIP
            "/HIPR",  // 9: RIGHT_HIP
            "/KNEL",  // 10: LEFT_KNEE
            "/KNER",  // 11: RIGHT_KNEE
            "/ANKL",  // 12: LEFT_ANKLE
            "/ANKR",  // 13: RIGHT_ANKLE
            "/EYEL",  // 14: LEFT_EYE
            "/EYER",  // 15: RIGHT_EYE
            "/EARL",  // 16: LEFT_EAR
            "/EARR",  // 17: RIGHT_EAR (Note: CSV may have this labeled differently)
        };
    }

    _enable_bones = _params.value("enable_bones", true);
    _enable_keypoints = _params.value("enable_keypoints", true);
    
    // Rate limiting configuration to prevent gRPC overload (enabled by default)
    _enable_rate_limiting = _params.value("enable_rate_limiting", true);
    int frame_delay_us = _params.value("frame_delay_microseconds", 5000); // 5ms default
    _min_frame_delay = std::chrono::microseconds(frame_delay_us);
    
    // Real-time time series visualization (enabled by default)
    _enable_timeseries = _params.value("enable_timeseries", true);

    // Load the keypaths configuration
    _keypaths.clear();
    if (_params.contains("keypaths") && _params["keypaths"].is_array()) {
      for (const auto &path : _params["keypaths"]) {
        if (path.is_string()) {
          _keypaths.push_back(path.get<std::string>());
        }
      }
    }

    // Load ACF configuration
    _acf_keypaths.clear();
    if (_params.contains("acf_keypaths") &&
        _params["acf_keypaths"].is_array()) {
      for (const auto &path : _params["acf_keypaths"]) {
        if (path.is_string()) {
          _acf_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }

    // Load FFT configuration
    _fft_keypaths.clear();
    if (_params.contains("fft_keypaths") &&
        _params["fft_keypaths"].is_array()) {
      for (const auto &path : _params["fft_keypaths"]) {
        if (path.is_string()) {
          _fft_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }

    // Load trace configuration
    _trace_keypaths.clear();
    if (_params.contains("trace_keypaths") &&
        _params["trace_keypaths"].is_array()) {
      for (const auto &path : _params["trace_keypaths"]) {
        if (path.is_string()) {
          _trace_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override {
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent

    return {{"Rerun version", rerun::version_string()},
            {"Window size", std::to_string(_window_size)},
            {"ACF Keypaths",
             _acf_keypaths.empty() ? "None" : json(_acf_keypaths).dump()},
            {"FFT Keypaths",
             _fft_keypaths.empty() ? "None" : json(_fft_keypaths).dump()},
            {"Trace Keypaths",
             _trace_keypaths.empty() ? "None" : json(_trace_keypaths).dump()},
            {"Keypaths", _keypaths.empty() ? "None" : json(_keypaths).dump()},
            {"Time column", _params["time"].get<string>().empty()
                                ? "timecode"
                                : _params["time"].get<std::string>()},
            {"Blueprint", (_blueprint.empty() ? "None" : _blueprint.string())},
            {"Parallelize", _params["parallelize"].get<bool>() ? to_string(_pool.get_thread_count()) + " threads" : "NO"}
          };
  };
};

/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
// On Windows, pugg plugin loading requires dlfcn.h which is not available
// The plugin can still be used directly via the main() function
INSTALL_SINK_DRIVER(RerunnerPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  RerunnerPlugin plugin;
  json input, params;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(&params);

  // Process data
  plugin.load_data(input);

  return 0;
}
