/*
  ____  _       _        _             _       
 / ___|(_)_ __ | | __  | |_ __  _   _| | __ _ _ _ __
 \___ \| | '_ \| |/ /  | '_ \| | | | | |/ _` | | '_ \
  ___) | | | | |   <   | |_) | | |_| | | (_| | | | | |
 |____/|_|_| |_|_|\_\  | .__/|_|\__,_|_|\__, |_|_| |_|
                       |_|               |___/
# A Template for RerunPlugin, a Sink Plugin
# Generated by the command: plugin -t sink -d rerun_plugin -s rerun
# Hostname: Fram-IV.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2025-09-08T16:35:50.334+0200
# NOTICE: MADS Version 1.3.5
*/

// Mandatory included headers
#include <nlohmann/json.hpp>
#include <sink.hpp>

// Include pugg on non-Windows platforms, or if we have dlfcn.h available

#include <pugg/Kernel.h>

#include "moving_window_stats.hpp"
#include "skeleton_definition.hpp"

#include <BS_thread_pool.hpp>
#include <array>
#include <chrono>
#include <datastore.hpp>
#include <deque>
#include <filesystem>
#include <future>
#include <memory>
#include <optional>
#include <rerun.hpp>
#include <unordered_map>
#include <vector>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "rerun"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
#include <deque>
#include <unordered_map>

class RerunnerPlugin : public Sink<json> {
private:
  // Skeleton configuration
  pose::SkeletonDefinition _skeleton;
  std::vector<std::string> _skeleton_keypoint_paths;

  bool _enable_skeleton = false;
  bool _enable_bones = true;
  bool _enable_keypoints = true;
  bool _use_confidence_colors = false;
  double _min_confidence = 0.0;

  std::vector<std::string> _keypaths;
  std::vector<std::string> _acf_keypaths;
  std::vector<std::string> _fft_keypaths;
  std::vector<std::string> _trace_keypaths;
  MovingWindowStats _stats;
  size_t _window_size = 1000; // Store 10x ACF width for better statistics
  filesystem::path _blueprint;
  
  // Real-time visualization settings
  bool _enable_timeseries = true; // Automatically enable time series

  std::chrono::steady_clock::time_point _start_time;
  std::shared_ptr<rerun::RecordingStream> _rec;

  BS::thread_pool<BS::tp::none> _pool;
  vector<future<bool>> _futures;
  
  // Rate limiting to prevent gRPC overload
  size_t _frame_count = 0;
  bool _enable_rate_limiting = true;
  std::chrono::microseconds _min_frame_delay{5000}; // 5ms default to prevent overload
  std::chrono::steady_clock::time_point _last_frame_time;

  // Helper function to convert dot notation path to JSON value
  json::json_pointer dot_to_pointer(const std::string &dot_path) {
    std::string result;
    std::string token;
    bool in_brackets = false;
    if (dot_path[0] == '/') 
      return json::json_pointer(dot_path);

    for (char c : dot_path) {
      if (c == '[') {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
        in_brackets = true;
      } else if (c == ']') {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
        in_brackets = false;
      } else if (c == '.' && !in_brackets) {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
      } else {
        token += c;
      }
    }

    if (!token.empty()) {
      result += "/" + token;
    }

    return json::json_pointer(result);
  }

  // Helper function to safely get a value from JSON using dot notation
  std::optional<double> get_numeric_value(const json &j,
                                          const std::string &dot_path) {
    json::json_pointer ptr = dot_to_pointer(dot_path);

    try {
      const auto &value = j[ptr];

      if (value.is_number()) {
        return value.get<double>();
      }
    } catch (const json::exception &e) {
      // Path doesn't exist or other JSON error
    }
    return std::nullopt;
  }

  // Helper: Extract 3D position from JSON keypath
  // Supports both /path/x, /path/y, /path/z AND /path/crd/0, /path/crd/1, /path/crd/2
  std::optional<std::array<double, 3>> 
  extract_3d_position(const json &data, const std::string &keypath) {
      // Try new format first: /JOINT/crd/0, /JOINT/crd/1, /JOINT/crd/2
      auto x_val = get_numeric_value(data, keypath + "/crd/0");
      auto y_val = get_numeric_value(data, keypath + "/crd/1");
      auto z_val = get_numeric_value(data, keypath + "/crd/2");
      
      // Fall back to old format: /path/x, /path/y, /path/z
      if (!x_val) x_val = get_numeric_value(data, keypath + "/x");
      if (!y_val) y_val = get_numeric_value(data, keypath + "/y");
      if (!z_val) z_val = get_numeric_value(data, keypath + "/z");
      
      if (x_val && y_val && z_val) {
          return std::array<double, 3>{*x_val, *y_val, *z_val};
      }
      return std::nullopt;
  }

  // Helper: Extract 2D position from JSON keypath
  std::optional<std::array<double, 2>> 
  extract_2d_position(const json &data, const std::string &keypath) {
      // Try new format first: /JOINT/crd/0, /JOINT/crd/1
      auto x_val = get_numeric_value(data, keypath + "/crd/0");
      auto y_val = get_numeric_value(data, keypath + "/crd/1");
      
      // Fall back to old format: /path/x, /path/y
      if (!x_val) x_val = get_numeric_value(data, keypath + "/x");
      if (!y_val) y_val = get_numeric_value(data, keypath + "/y");
      
      if (x_val && y_val) {
          return std::array<double, 2>{*x_val, *y_val};
      }
      return std::nullopt;
  }

  // Helper: Extract confidence from covariance matrix
  // HPE format uses /JOINT/unc/0 through /JOINT/unc/5 as a 3x3 covariance matrix
  // Returns confidence as 1/(1 + trace), where lower covariance = higher confidence
  std::optional<double>
  extract_confidence(const json &data, const std::string &keypath) {
      // Try to extract the 6 covariance components (3x3 symmetric matrix)
      // unc/0: var_x, unc/1: var_y, unc/2: var_z, unc/3: cov_xy, unc/4: cov_xz, unc/5: cov_yz
      auto var_x = get_numeric_value(data, keypath + "/unc/0");
      auto var_y = get_numeric_value(data, keypath + "/unc/1");
      auto var_z = get_numeric_value(data, keypath + "/unc/2");
      
      if (var_x && var_y && var_z) {
          // Calculate trace of covariance matrix (sum of diagonal elements)
          double trace = *var_x + *var_y + *var_z;
          // Convert to confidence: lower covariance = higher confidence
          // Using 1/(1 + trace) to normalize to [0, 1] range
          double confidence = 1.0 / (1.0 + trace);
          return confidence;
      }
      
      // Fall back to standard format: /JOINT/confidence
      auto conf_val = get_numeric_value(data, keypath + "/confidence");
      return conf_val;
  }

  // Color by confidence (red=low, green=high)
  rerun::Color confidence_to_color(double confidence) {
      confidence = std::max(0.0, std::min(1.0, confidence));
      uint8_t red = static_cast<uint8_t>((1.0 - confidence) * 255);
      uint8_t green = static_cast<uint8_t>(confidence * 255);
      return rerun::Color(red, green, 100, 255);
  }

  // Main skeleton visualization function
  bool log_skeleton_visualization(const json &data, double time_seconds) {
      if (!_enable_skeleton || _skeleton_keypoint_paths.empty()) {
          return false;
      }
      
      bool logged = false;
      std::vector<rerun::Position3D> positions_3d;
      std::vector<float> confidences;
      std::vector<rerun::Color> colors;
      
      // Extract all keypoints
      for (size_t i = 0; i < _skeleton_keypoint_paths.size(); ++i) {
          const auto& kp_path = _skeleton_keypoint_paths[i];
          double conf = 1.0;
          
          if (auto conf_val = extract_confidence(data, kp_path)) {
              conf = *conf_val;
          }
          
          confidences.push_back(static_cast<float>(conf));
          rerun::Color color = _use_confidence_colors 
              ? confidence_to_color(conf)
              : rerun::Color(0, 255, 0, 255);
          colors.push_back(color);
          
          if (auto pos = extract_3d_position(data, kp_path)) {
              positions_3d.push_back(rerun::Position3D(pos->at(0), pos->at(1), pos->at(2)));
          } 
          else if (auto pos2d = extract_2d_position(data, kp_path)) {
              positions_3d.push_back(rerun::Position3D(pos2d->at(0), pos2d->at(1), 0.0));
          }
          else {
              positions_3d.push_back(rerun::Position3D(0, 0, 0));
          }
      }
      
      // Log keypoints
      if (_enable_keypoints && !positions_3d.empty()) {
          auto points_entity = rerun::Points3D(positions_3d)
              .with_colors(colors)
              .with_radii({0.02f});
          
          _rec->log("skeleton/keypoints", points_entity);
          logged = true;
      }
      
      // Log bones
      if (_enable_bones && !positions_3d.empty() && _skeleton.bone_count() > 0) {
          std::vector<rerun::Position3D> bone_points;
          std::vector<rerun::Color> bone_colors;
          
          for (const auto& bone : _skeleton.bones()) {
              if (bone.start_joint < positions_3d.size() && 
                  bone.end_joint < positions_3d.size()) {
                  
                  bool start_valid = confidences[bone.start_joint] >= _min_confidence;
                  bool end_valid = confidences[bone.end_joint] >= _min_confidence;
                  
                  if (start_valid && end_valid) {
                      bone_points.push_back(rerun::Position3D(positions_3d[bone.start_joint]));
                      bone_points.push_back(rerun::Position3D(positions_3d[bone.end_joint]));
                      
                      double avg_conf = (confidences[bone.start_joint] + 
                                        confidences[bone.end_joint]) / 2.0;
                      bone_colors.push_back(confidence_to_color(avg_conf));
                      bone_colors.push_back(confidence_to_color(avg_conf));
                  }
              }
          }
          
          if (!bone_points.empty()) {
              std::vector<uint32_t> strip_lengths;
              for (size_t i = 0; i < bone_points.size(); i += 2) {
                  strip_lengths.push_back(2);
              }
              
              auto bones_entity = rerun::LineStrips3D(bone_points)
                  .with_colors(bone_colors);
              
              _rec->log("skeleton/bones", bones_entity);
              logged = true;
          }
      }
      
      return logged;
  }

public:
  RerunnerPlugin() {
    _start_time = std::chrono::steady_clock::now();
    _last_frame_time = _start_time;
    _frame_count = 0;
  }

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "") override {
    static double prev_time = 0;
    static double mean_dt = 0;
    static size_t n = 0;
    double dt = 0;
    bool logged = false;
    if (topic.empty()) {
      _error = "No topic specified in plugin load_data()";
      return return_type::error;
    }

    auto now = std::chrono::steady_clock::now();
    double time_seconds;
    // get the timecode from the input json if available, otherwise use elapsed
    // time
    if (!_params["time"].empty() && input.contains(_params["time"])) {
      time_seconds = input[_params["time"]].get<double>();
    } else {
      time_seconds = std::chrono::duration<double>(now - _start_time).count();
    }

    dt = time_seconds - prev_time;

    // embed the input json within a parent object named as the topic
    // keep a copy (no move) so we can attempt alternative lookup paths
    json data = json{{topic, input}};
    
    // Rate limiting: prevent flooding gRPC connection
    if (_enable_rate_limiting && _frame_count > 0) {
      auto now_time = std::chrono::steady_clock::now();
      auto elapsed = std::chrono::duration_cast<std::chrono::microseconds>(now_time - _last_frame_time);
      if (elapsed < _min_frame_delay) {
        std::this_thread::sleep_for(_min_frame_delay - elapsed);
      }
      _last_frame_time = std::chrono::steady_clock::now();
    } else if (_frame_count == 0) {
      _last_frame_time = std::chrono::steady_clock::now();
    }
    
    // Set the current time for this batch of data
    // This is crucial for time series visualization - all subsequent logs will use this timestamp
    try {
      _rec->set_time_seconds("time", time_seconds);
    } catch (const std::exception& e) {
      // Silently handle timing errors - don't fail the entire frame
      if (_frame_count % 100 == 0) {
        _error = "Warning: Rerun timing error: " + std::string(e.what());
      }
    }
    
    // Debug: Log that we're processing data (only for first few frames)
    if (n < 5) {
      try {
        _rec->log("debug/info", rerun::TextLog("Processing frame " + std::to_string(n) + 
                                               " for topic: " + topic + 
                                               " at time: " + std::to_string(time_seconds)));
      } catch (const std::exception& e) {
        // Ignore debug log errors
      }
    }

    // Extract values for each keypath and send to rerun as time series
    // Real-time visualization enabled by default
    if (_enable_timeseries && !_keypaths.empty()) {
      for (const auto &keypath : _keypaths) {
        if (auto value = get_numeric_value(data, keypath)) {
          try {
            // Log raw data point on the timeline for real-time visualization
            _rec->log("timeseries/" + keypath, rerun::Scalars(*value));
            logged = true;
          } catch (const std::exception& e) {
            if (_frame_count % 100 == 0) {
              _error = "Rerun gRPC error (timeseries/keypaths): " + std::string(e.what());
            }
          }
        }
      }
    }

    // Log skeleton visualization if enabled
    if (_enable_skeleton && !_skeleton_keypoint_paths.empty()) {
        std::vector<rerun::Position3D> positions;
        std::vector<float> confidences;
        
        // Extract all keypoint positions and log coordinates as time series
        for (size_t i = 0; i < _skeleton_keypoint_paths.size(); ++i) {
          const auto& kp_path = _skeleton_keypoint_paths[i];

          // Build alternative paths to match incoming JSON keys
          const std::string full_path = "/" + topic + kp_path;        // e.g. /topic/ANKL
          const std::string raw_path = kp_path;                        // e.g. /ANKL
          const std::string topic_prefixed_no_slash = topic + kp_path; // e.g. topic/ANKL

          std::optional<std::array<double, 3>> pos;
          pos = extract_3d_position(data, full_path);
          if (!pos) pos = extract_3d_position(data, raw_path);
          if (!pos) pos = extract_3d_position(data, topic_prefixed_no_slash);
            
          if (pos) {
            positions.push_back(rerun::Position3D(pos->at(0), pos->at(1), pos->at(2)));

            // Confidence: try matching paths; default to 1.0 if missing
            auto conf = extract_confidence(data, full_path);
            if (!conf) conf = extract_confidence(data, raw_path);
            if (!conf) conf = extract_confidence(data, topic_prefixed_no_slash);
            confidences.push_back(static_cast<float>(conf.value_or(1.0)));
                
            // Log individual joint coordinates as time series for real-time visualization
            // Log a combined 3D scalar to reduce number of messages
            if (_enable_timeseries) {
              std::string joint_name = kp_path;
              if (joint_name.front() == '/') {
                joint_name = joint_name.substr(1);
              }
                  
              try {
                // Log X, Y, Z as separate scalar for better time series visualization
                // Only log every frame - rate limiting handles the flow control
                _rec->log("timeseries/skeleton/" + joint_name + "/x", rerun::Scalars(pos->at(0)));
                _rec->log("timeseries/skeleton/" + joint_name + "/y", rerun::Scalars(pos->at(1)));
                _rec->log("timeseries/skeleton/" + joint_name + "/z", rerun::Scalars(pos->at(2)));
                logged = true;
              } catch (const std::exception& e) {
                // gRPC connection error - disable timeseries temporarily
                _enable_timeseries = false;
                _error = "Rerun gRPC error - disabling timeseries: " + std::string(e.what());
                break; // Exit the loop to prevent further errors
              }
            }
          }
        }
        
        // Log keypoints in 3D view
        if (_enable_keypoints && !positions.empty()) {
            // Create colored points based on confidence
            std::vector<rerun::Color> colors;
            for (float conf : confidences) {
                uint8_t green = static_cast<uint8_t>(conf * 255);
                colors.push_back(rerun::Color(0, green, 0, 255));
            }
            
            try {
              _rec->log("skeleton/keypoints",
                        rerun::Points3D(positions)
                            .with_colors(colors)
                            .with_radii({0.02f}));
              logged = true;
            } catch (const std::exception& e) {
              // gRPC connection error
              if (_frame_count % 100 == 0) {
                _error = "Rerun gRPC error (keypoints): " + std::string(e.what());
              }
            }
        }
        
        // Log bones in 3D view
        if (_enable_bones && !positions.empty()) {
            std::vector<rerun::Position3D> bone_points;
            std::vector<rerun::Color> bone_colors;
            std::vector<uint32_t> strip_lengths;
            
            for (const auto& bone : _skeleton.bones()) {
                if (bone.start_joint < positions.size() && 
                    bone.end_joint < positions.size() &&
                    bone.start_joint < confidences.size() &&
                    bone.end_joint < confidences.size()) {
                    
                    // Check confidence threshold
                    if (confidences[bone.start_joint] >= _min_confidence &&
                        confidences[bone.end_joint] >= _min_confidence) {
                        
                        bone_points.push_back(positions[bone.start_joint]);
                        bone_points.push_back(positions[bone.end_joint]);
                        
                        // Calculate average confidence color for this bone
                        float avg_conf = (confidences[bone.start_joint] + confidences[bone.end_joint]) / 2.0f;
                        uint8_t red = static_cast<uint8_t>((1.0f - avg_conf) * 255);
                        uint8_t green = static_cast<uint8_t>(avg_conf * 255);
                        rerun::Color bone_color(red, green, 0, 255);
                        
                        bone_colors.push_back(bone_color);
                        bone_colors.push_back(bone_color);
                        strip_lengths.push_back(2);
                    }
                }
            }
            
            if (!bone_points.empty()) {
                try {
                  _rec->log("skeleton/bones",
                            rerun::LineStrips3D(bone_points)
                                .with_colors(bone_colors));
                  logged = true;
                } catch (const std::exception& e) {
                  // gRPC connection error
                  if (_frame_count % 100 == 0) {
                    _error = "Rerun gRPC error (bones): " + std::string(e.what());
                  }
                }
            }
        }
    }

    if (logged) {
      prev_time = time_seconds;
      n++;
      _frame_count++;
      
      // Ensure data is flushed to Rerun (helps with real-time visualization)
      // Note: This may slow down processing but ensures data is sent
      
      return return_type::success;
    } else {
      // No data was logged - this could indicate a configuration issue
      _frame_count++;
      return return_type::success;
    }
  }

  void set_params(void const *params) override {
    // Call the parent class method to set the common parameters
    // (e.g. agent_id, etc.)
    Sink::set_params(params);

    // provide sensible defaults for the parameters
    _params["keypaths"] = json::array();       // empty array by default
    _params["acf_keypaths"] = json::array();   // empty array by default
    _params["fft_keypaths"] = json::array();   // empty array by default
    _params["trace_keypaths"] = json::array(); // empty array by default
    _params["window_size"] = 100;              // default ACF width
    _params["time"] = "timecode";
    _params["blueprint"] = "";
    _params["parallelize"] = true;

    // then merge the defaults with the actually provided parameters
    _params.merge_patch(*(json *)params);
    _window_size = _params.value("window_size", 200);
    _stats.reset(_window_size);

    // Initialize Rerun with real-time optimized settings
    _rec = std::make_shared<rerun::RecordingStream>("MADS " + _params.value("agent_name", "rerunner (generic)"));
    _rec->spawn().exit_on_failure();

    if (!_agent_id.empty()) {
      _rec->send_recording_name(_agent_id);
    }

    _blueprint = _params.value("blueprint", "");
    if (filesystem::exists(_blueprint)) {
      _rec->log_file_from_path(_blueprint);
    } else if (!_blueprint.empty()) {
      _blueprint = _params.value("blueprint", "") + " (not found)";
    }

    // Load skeleton configuration
    if (_params.contains("skeleton_type")) {
        std::string skeleton_type = _params["skeleton_type"].get<std::string>();
        if (skeleton_type == "hpe_18") {
            _skeleton = pose::SkeletonDefinition::hpe_18();
        } else {
            // Default to HPE 18 for HPE replay datasets
            _skeleton = pose::SkeletonDefinition::hpe_18();
        }
        _enable_skeleton = true;
    } else {
        // Default skeleton
        _skeleton = pose::SkeletonDefinition::hpe_18();
        _enable_skeleton = true;
    }

    // Load keypoint paths
    _skeleton_keypoint_paths.clear();
    if (_params.contains("skeleton_keypoint_paths") && 
        _params["skeleton_keypoint_paths"].is_array()) {
        for (const auto &path : _params["skeleton_keypoint_paths"]) {
            if (path.is_string()) {
                _skeleton_keypoint_paths.push_back(path.get<std::string>());
            }
        }
    } else {
        // Auto-configure HPE 18-joint keypoint paths from CSV structure
        // Each joint has format /JOINT_NAME/crd/X for coordinates
        _skeleton_keypoint_paths = {
            "/NOS_",  // 0: NOSE
            "/NEC_",  // 1: NECK
            "/SHOL",  // 2: LEFT_SHOULDER
            "/SHOR",  // 3: RIGHT_SHOULDER
            "/ELBL",  // 4: LEFT_ELBOW
            "/ELBR",  // 5: RIGHT_ELBOW
            "/WRIL",  // 6: LEFT_WRIST
            "/WRIR",  // 7: RIGHT_WRIST
            "/HIPL",  // 8: LEFT_HIP
            "/HIPR",  // 9: RIGHT_HIP
            "/KNEL",  // 10: LEFT_KNEE
            "/KNER",  // 11: RIGHT_KNEE
            "/ANKL",  // 12: LEFT_ANKLE
            "/ANKR",  // 13: RIGHT_ANKLE
            "/EYEL",  // 14: LEFT_EYE
            "/EYER",  // 15: RIGHT_EYE
            "/EARL",  // 16: LEFT_EAR
            "/EARR",  // 17: RIGHT_EAR (Note: CSV may have this labeled differently)
        };
    }

    _enable_bones = _params.value("enable_bones", true);
    _enable_keypoints = _params.value("enable_keypoints", true);
    _min_confidence = _params.value("min_confidence", 0.1);
    _use_confidence_colors = _params.value("use_confidence_colors", true);
    
    // Rate limiting configuration to prevent gRPC overload (enabled by default)
    _enable_rate_limiting = _params.value("enable_rate_limiting", true);
    int frame_delay_us = _params.value("frame_delay_microseconds", 5000); // 5ms default
    _min_frame_delay = std::chrono::microseconds(frame_delay_us);
    
    // Real-time time series visualization (enabled by default)
    _enable_timeseries = _params.value("enable_timeseries", true);

    // Load the keypaths configuration
    _keypaths.clear();
    if (_params.contains("keypaths") && _params["keypaths"].is_array()) {
      for (const auto &path : _params["keypaths"]) {
        if (path.is_string()) {
          _keypaths.push_back(path.get<std::string>());
        }
      }
    }

    // Load ACF configuration
    _acf_keypaths.clear();
    if (_params.contains("acf_keypaths") &&
        _params["acf_keypaths"].is_array()) {
      for (const auto &path : _params["acf_keypaths"]) {
        if (path.is_string()) {
          _acf_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }

    // Load FFT configuration
    _fft_keypaths.clear();
    if (_params.contains("fft_keypaths") &&
        _params["fft_keypaths"].is_array()) {
      for (const auto &path : _params["fft_keypaths"]) {
        if (path.is_string()) {
          _fft_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }

    // Load trace configuration
    _trace_keypaths.clear();
    if (_params.contains("trace_keypaths") &&
        _params["trace_keypaths"].is_array()) {
      for (const auto &path : _params["trace_keypaths"]) {
        if (path.is_string()) {
          _trace_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override {
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent

    return {{"Rerun version", rerun::version_string()},
            {"Window size", std::to_string(_window_size)},
            {"ACF Keypaths",
             _acf_keypaths.empty() ? "None" : json(_acf_keypaths).dump()},
            {"FFT Keypaths",
             _fft_keypaths.empty() ? "None" : json(_fft_keypaths).dump()},
            {"Trace Keypaths",
             _trace_keypaths.empty() ? "None" : json(_trace_keypaths).dump()},
            {"Keypaths", _keypaths.empty() ? "None" : json(_keypaths).dump()},
            {"Time column", _params["time"].get<string>().empty()
                                ? "timecode"
                                : _params["time"].get<std::string>()},
            {"Blueprint", (_blueprint.empty() ? "None" : _blueprint.string())},
            {"Parallelize", _params["parallelize"].get<bool>() ? to_string(_pool.get_thread_count()) + " threads" : "NO"}
          };
  };
};

/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
// On Windows, pugg plugin loading requires dlfcn.h which is not available
// The plugin can still be used directly via the main() function
INSTALL_SINK_DRIVER(RerunnerPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  RerunnerPlugin plugin;
  json input, params;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(&params);

  // Process data
  plugin.load_data(input);

  return 0;
}
